services:
  ros2:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ros
    container_name: ros2_container
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./:/ros_workspace
    devices:
      - /dev/dri
      - "/dev/video0:/dev/video0"
    group_add:
      - video
    network_mode: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  px4:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.px4
    container_name: px4_container
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./PX4-Autopilot:/PX4-Autopilot
    devices:
      - /dev/dri
    group_add:
      - video
    network_mode: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]